on: push
jobs:
  gcc:
    uses: ./.github/workflows/common_cmake.yml
    with:
      c-compiler: gcc
      cpp-compiler: g++

  clang:
    uses: ./.github/workflows/common_cmake.yml
    with:
      c-compiler: clang
      cpp-compiler: clang++

  cl:
    uses: ./.github/workflows/common_cmake.yml
    with:
      c-compiler: cl
      cpp-compiler: cl
      os: windows-latest

  gcc-coverage:
    uses: ./.github/workflows/common_cmake.yml
    with:
      c-compiler: gcc
      cpp-compiler: g++
      build-type: Debug
      cmake-test-arguments: |
        -D BuildWithCoverage=ON
      coverage: true
    secrets: inherit


