
on: push
jobs:
  gcc:
    uses: ./.github/workflows/common_cmake.yml
    with:
      c-compiler: gcc
      cpp-compiler: g++

  clang:
    uses: ./.github/workflows/common_cmake.yml
    with:
      c-compiler: clang
      cpp-compiler: clang++

  cl:
    uses: ./.github/workflows/common_cmake.yml
    with:
      c-compiler: cl
      cpp-compiler: cl
      os: windows-latest

  gcc-collect-coverage:
      if: ${{ github.ref_name == 'main' || github.ref_name == '15-automate-code-coverage-badge' }}
      uses: ./.github/workflows/common_cmake.yml
      with:
        c-compiler: gcc
        cpp-compiler: g++
        build-type: Debug
        cxx-test-flags: "--coverage"
        artifacts-path: |
          *.gcda
          *.gcno

  create-coverage-badge:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || github.ref_name == '15-automate-code-coverage-badge' }}
    needs: [gcc-collect-coverage]
    steps:
      - name: Create Coverage Badge
        id: coverage
        run: |
            sudo apt-get install lcov -y
            lcov --capture --directory . --output-file coverage.info
            a_percentage=$(lcov --list coverage.info | grep -oP '^\s*\d+\.\d+%' | head -n 1)
            echo "coverage-percent-value=${a_percentage}" >> "$GITHUB_OUTPUT"
      - name: Build A Badge
        uses: peterrhodesdev/build-a-badge@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: "badges/coverage-badge"
          label: "Coverage"
          message: "${{steps.coverage.outputs.coverage-percent-value}}"

        
    