on: push

jobs:
  ReleaseBuilds:
    strategy:
      matrix:
        os: [ubuntu-latest]
        c-compiler: [gcc, clang]
        include:
          - c-compiler: gcc
            cpp-compiler: g++
          - c-compiler: clang
            cpp-compiler: clang++
          - c-compiler: cl
            cpp-compiler: cl
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - &setup-dirs
      name: Set reusable strings
      shell: bash
      # Turn repeated input strings (such as the build output directory) into step outputs.
      id: strings
      # absolute paths do not work on Windows runners so these are rarely used
      #  (\ is not escaped so bad stuff happens)
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "install-dir=${{ github.workspace }}/installed" >> "$GITHUB_OUTPUT"
        echo "build-test-dir=${{ github.workspace }}/build_test" >> "$GITHUB_OUTPUT"
        echo "cmake_args=-DCMAKE_CXX_COMPILER=${{ matrix.cpp-compiler }} -DCMAKE_C_COMPILER=${{ matrix.c-compiler }} " >> "$GITHUB_OUTPUT"

    - &config 
      name: Configure CMake
      run: >
        cmake -B build
        -S ${{ github.workspace }}
        -DCMAKE_BUILD_TYPE=Release
        ${{ steps.strings.outputs.cmake_args }}

    - &build-code
      name: Build
      # Does (mostly) nothing, required for install step 
      run: cmake --build build --config Release

    - &install-code
      name: Install
      # Install our cmake package
      run: >
        cmake --install build
        --config Release
        --prefix ${{ github.workspace }}/installed

    - &config-tests 
      name: Test Configure
      run: >
        cmake -B build_test
        -S ./tests 
        -DCMAKE_BUILD_TYPE=Release
        ${{ steps.strings.outputs.cmake_args }}
        -D BuildExamples=ON
        -D BuildInternalTests=ON
        -D CMAKE_PREFIX_PATH=${{ github.workspace }}/installed
        
    - &build-tests
      name: Build Tests
      id: build-tests
      run: >
        cmake --build build_test --config Release

    - &run-tests
      name: Run Tests
      id: run-tests
      if: ${{steps.build-tests.outcome == 'success'}}
      working-directory: ${{ steps.strings.outputs.build-test-dir }}
      # Execute tests. Note that --build-config is needed (see build)
      run: |
        ctest --build-config Release --output-on-failure

  gcc-coverage:
    # Matrix is just so that the YAML anchors work
    strategy:
      matrix:
        include:
        - c-compiler: gcc
          cpp-compiler: g++
          os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - *setup-dirs
    - &config-coverage
      name: Configure CMake with Coverage
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}
        ${{ steps.strings.outputs.cmake_args }}
        -D build_testing=ON
        -D BuildExamples=ON
        -D BuildInternalTests=ON
        -D BuildWithCoverage=ON
        -DCMAKE_BUILD_TYPE=Debug
    - *build-code
    - name: Run Tests with Coverage
      id: run-tests
      working-directory: ${{ steps.strings.outputs.build-output-dir }}  
      run: |
        ctest --build-config Debug --output-on-failure
    - name: Coverage Reporting
      # Only run coverage if gcc is used and build type is Debug (for less inlining)
      id: coverage
      # Install gcovr
      # Get coverage in normal format and print
      # Get coverage as single percentage
      # Write it to output for use later
      # Should always be 100%
      run: |
       sudo apt-get install gcovr -y
       gcovr -r ${{ steps.strings.outputs.build-output-dir }} -f 'CppUnit*' -s -o coverage.txt
       percent=$(cat coverage.txt | grep TOTAL | grep -oP '\d+%')
       echo "coverage-percent-value=$percent" >> "$GITHUB_OUTPUT"

    - name: Build Coverage Badge
      if: ${{ github.ref_name == 'main' }}
      uses: peterrhodesdev/build-a-badge@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filename: "coverage-badge-data"
        label: "Coverage"
        namedLogo: 'github'
        color: "brightgreen"
        message: "${{steps.coverage.outputs.coverage-percent-value}}"
  
  compiler-warnings:
    # - name: Test compile with Wextra and Wall
    # Matrix is just so that the YAML anchors work
    strategy:
      matrix:
        include:
        - c-compiler: gcc
          cpp-compiler: g++
          os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - *setup-dirs
    - name: Configure CMake with Mutation Testing
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}
        ${{ steps.strings.outputs.cmake_args }}
        -D build_testing=ON
        -D BuildExamples=OFF
        -D BuildInternalTests=ON
        -DEnableMainHelperClasses=ON
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wconversion -Werror"
    - *build-code
    - *run-tests

  mutation-testing:
    strategy:
      matrix:
        include:
          # must be a fixed version of clang for mull to work
        - c-compiler: clang-18
          cpp-compiler: clang++-18
          os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - *setup-dirs
    - name: Install Mull
      run: |
        curl -1sLf 'https://dl.cloudsmith.io/public/mull-project/mull-stable/setup.deb.sh' | sudo -E bash
        sudo apt-get install mull-18
        mull-runner-18 --version
    - &config-mutation
      name: Configure CMake with Mutation Testing
      # O0 is on for debug anyway.
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}
        ${{ steps.strings.outputs.cmake_args }}
        -D build_testing=ON
        -D BuildExamples=ON
        -D BuildInternalTests=ON
        -D BuildUnityTests=ON
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_FLAGS="-O0 -fpass-plugin=/usr/lib/mull-ir-frontend-18 -g -grecord-command-line"
    - *build-code
    - &run-mutation-tests
      name: Run Mutation Tests
      id: mutation-tests  
      run: |
        mull-runner-18 --workers=6 ./build/tests/CppUnit2Gtest_AllTests | tee mutation_report.txt
        percent=$(cat mutation_report.txt | grep "Mutation score: " | grep -oP '\d+%')
        echo "mutation-percent-value=$percent" >> "$GITHUB_OUTPUT"
    - &mutation-badge
      name: Build Mutation Testing Badge
      if: ${{ github.ref_name == 'main' }}
      uses: peterrhodesdev/build-a-badge@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filename: "mutation-badge-data"
        label: "Mutation Test Score"
        namedLogo: 'github'
        color: "brightgreen"
        message: "${{steps.mutation-tests.outputs.mutation-percent-value}}"

